import type { Metadata, Viewport } from "next";
import { Oswald } from 'next/font/google'
import "./globals.css";
// import { ThemeProvider } from "@/components/ui/Theme-provider";
import { ThemeColorMeta } from "@/components/ui/Theme-color-meta";

const oswald = Oswald({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-Oswald'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
  lang="en"
  className={`${oswald.variable} h-full antialiased`}
  suppressHydrationWarning
>
  <body className="h-full">
    {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
      <ThemeColorMeta />
      <div className="h-dvh overflow-y-auto overscroll-y-contain">
        {children}
      </div>
    {/* </ThemeProvider> */}
  </body>
</html>
  );
}