export const workoutData = {
  fullbody: {
    split: "Full Body",
    description:
      "Full body workout targeting all major muscle groups each session",
    frequency: 3,
    workouts: [
      {
        day: "Day 1",
        focus: "Full Body",
        exercises: [
          {
            name: "Barbell Squat",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "8-10",
          },
          { name: "Bench Press", muscleGroup: "Chest", sets: 4, reps: "8-10" },
          {
            name: "Bent Over Rows",
            muscleGroup: "Back",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Overhead Press",
            muscleGroup: "Shoulders",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Romanian Deadlifts",
            muscleGroup: "Hamstrings",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Cable Tricep Pushdown",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "12-15",
          },
          { name: "Leg Raises", muscleGroup: "Abs", sets: 3, reps: "15-20" },
        ],
      },
      {
        day: "Day 2",
        focus: "Full Body",
        exercises: [
          { name: "Deadlift", muscleGroup: "Back", sets: 4, reps: "6-8" },
          {
            name: "Incline Dumbbell Press",
            muscleGroup: "Chest",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Leg Press",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "10-12",
          },
          {
            name: "Lat Pulldowns",
            muscleGroup: "Back",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Dumbbell Lateral Raises",
            muscleGroup: "Shoulders",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Hamstring Curls",
            muscleGroup: "Hamstrings",
            sets: 3,
            reps: "12-15",
          },
          { name: "Plank", muscleGroup: "Abs", sets: 3, reps: "60s" },
        ],
      },
      {
        day: "Day 3",
        focus: "Full Body",
        exercises: [
          {
            name: "Front Squat",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "8-10",
          },
          { name: "Pull-Ups", muscleGroup: "Back", sets: 4, reps: "Max" },
          {
            name: "Dumbbell Press",
            muscleGroup: "Chest",
            sets: 4,
            reps: "10-12",
          },
          {
            name: "Leg Extensions",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Face Pulls",
            muscleGroup: "Shoulders",
            sets: 3,
            reps: "15-20",
          },
          {
            name: "Cable Curls",
            muscleGroup: "Biceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Russian Twists",
            muscleGroup: "Abs",
            sets: 3,
            reps: "20-25",
          },
        ],
      },
    ],
  },
  abc: {
    split: "ABC Split",
    description: "3-day split focusing on different muscle groups each session",
    frequency: 3,
    workouts: [
      {
        day: "Day A",
        focus: "Chest, Shoulders, Triceps",
        exercises: [
          { name: "Bench Press", muscleGroup: "Chest", sets: 4, reps: "8-10" },
          {
            name: "Incline Dumbbell Press",
            muscleGroup: "Chest",
            sets: 4,
            reps: "10-12",
          },
          { name: "Cable Flyes", muscleGroup: "Chest", sets: 3, reps: "12-15" },
          {
            name: "Overhead Press",
            muscleGroup: "Shoulders",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Dumbbell Lateral Raises",
            muscleGroup: "Shoulders",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Tricep Dips",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Cable Tricep Pushdown",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Day B",
        focus: "Back, Biceps",
        exercises: [
          { name: "Deadlift", muscleGroup: "Back", sets: 4, reps: "6-8" },
          { name: "Pull-Ups", muscleGroup: "Back", sets: 4, reps: "Max" },
          {
            name: "Bent Over Rows",
            muscleGroup: "Back",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Lat Pulldowns",
            muscleGroup: "Back",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Seated Cable Rows",
            muscleGroup: "Back",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Barbell Curls",
            muscleGroup: "Biceps",
            sets: 4,
            reps: "10-12",
          },
          {
            name: "Hammer Curls",
            muscleGroup: "Biceps",
            sets: 3,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Day C",
        focus: "Legs, Abs",
        exercises: [
          {
            name: "Barbell Squat",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Romanian Deadlifts",
            muscleGroup: "Hamstrings",
            sets: 4,
            reps: "10-12",
          },
          {
            name: "Leg Press",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Leg Extensions",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Hamstring Curls",
            muscleGroup: "Hamstrings",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Standing Calf Raises",
            muscleGroup: "Calves",
            sets: 4,
            reps: "15-20",
          },
          {
            name: "Hanging Leg Raises",
            muscleGroup: "Abs",
            sets: 4,
            reps: "12-15",
          },
        ],
      },
    ],
  },
  abcd: {
    split: "ABCD Split",
    description: "4-day split for more focused training",
    frequency: 4,
    workouts: [
      {
        day: "Day A",
        focus: "Chest, Triceps",
        exercises: [
          { name: "Bench Press", muscleGroup: "Chest", sets: 4, reps: "6-8" },
          {
            name: "Incline Barbell Press",
            muscleGroup: "Chest",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Dumbbell Flyes",
            muscleGroup: "Chest",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Cable Crossover",
            muscleGroup: "Chest",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Close Grip Bench Press",
            muscleGroup: "Triceps",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Tricep Rope Pushdown",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Overhead Tricep Extension",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Day B",
        focus: "Back, Biceps",
        exercises: [
          { name: "Deadlift", muscleGroup: "Back", sets: 4, reps: "5-7" },
          { name: "Pull-Ups", muscleGroup: "Back", sets: 4, reps: "Max" },
          { name: "Barbell Rows", muscleGroup: "Back", sets: 4, reps: "8-10" },
          {
            name: "Lat Pulldowns",
            muscleGroup: "Back",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Seated Cable Rows",
            muscleGroup: "Back",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Barbell Curls",
            muscleGroup: "Biceps",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Incline Dumbbell Curls",
            muscleGroup: "Biceps",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Hammer Curls",
            muscleGroup: "Biceps",
            sets: 3,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Day C",
        focus: "Shoulders, Abs",
        exercises: [
          {
            name: "Overhead Press",
            muscleGroup: "Shoulders",
            sets: 4,
            reps: "6-8",
          },
          {
            name: "Dumbbell Shoulder Press",
            muscleGroup: "Shoulders",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Dumbbell Lateral Raises",
            muscleGroup: "Shoulders",
            sets: 4,
            reps: "12-15",
          },
          {
            name: "Face Pulls",
            muscleGroup: "Shoulders",
            sets: 4,
            reps: "15-20",
          },
          {
            name: "Barbell Shrugs",
            muscleGroup: "Shoulders",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Hanging Leg Raises",
            muscleGroup: "Abs",
            sets: 4,
            reps: "12-15",
          },
          {
            name: "Cable Crunches",
            muscleGroup: "Abs",
            sets: 3,
            reps: "15-20",
          },
          { name: "Plank", muscleGroup: "Abs", sets: 3, reps: "60s" },
        ],
      },
      {
        day: "Day D",
        focus: "Legs",
        exercises: [
          {
            name: "Barbell Squat",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "6-8",
          },
          {
            name: "Romanian Deadlifts",
            muscleGroup: "Hamstrings",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Leg Press",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "10-12",
          },
          {
            name: "Walking Lunges",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Leg Extensions",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Hamstring Curls",
            muscleGroup: "Hamstrings",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Standing Calf Raises",
            muscleGroup: "Calves",
            sets: 5,
            reps: "15-20",
          },
          {
            name: "Seated Calf Raises",
            muscleGroup: "Calves",
            sets: 4,
            reps: "15-20",
          },
        ],
      },
    ],
  },
  upperlower: {
    split: "Upper/Lower",
    description: "Alternating upper and lower body workouts",
    frequency: 4,
    workouts: [
      {
        day: "Upper Day 1",
        focus: "Upper Body",
        exercises: [
          { name: "Bench Press", muscleGroup: "Chest", sets: 4, reps: "6-8" },
          {
            name: "Bent Over Rows",
            muscleGroup: "Back",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Overhead Press",
            muscleGroup: "Shoulders",
            sets: 3,
            reps: "8-10",
          },
          { name: "Pull-Ups", muscleGroup: "Back", sets: 3, reps: "Max" },
          {
            name: "Incline Dumbbell Press",
            muscleGroup: "Chest",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Barbell Curls",
            muscleGroup: "Biceps",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Tricep Dips",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "10-12",
          },
        ],
      },
      {
        day: "Lower Day 1",
        focus: "Lower Body",
        exercises: [
          {
            name: "Barbell Squat",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "6-8",
          },
          {
            name: "Romanian Deadlifts",
            muscleGroup: "Hamstrings",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Leg Press",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Leg Extensions",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Hamstring Curls",
            muscleGroup: "Hamstrings",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Standing Calf Raises",
            muscleGroup: "Calves",
            sets: 4,
            reps: "15-20",
          },
          {
            name: "Hanging Leg Raises",
            muscleGroup: "Abs",
            sets: 3,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Upper Day 2",
        focus: "Upper Body",
        exercises: [
          {
            name: "Incline Bench Press",
            muscleGroup: "Chest",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Lat Pulldowns",
            muscleGroup: "Back",
            sets: 4,
            reps: "10-12",
          },
          {
            name: "Dumbbell Shoulder Press",
            muscleGroup: "Shoulders",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Seated Cable Rows",
            muscleGroup: "Back",
            sets: 3,
            reps: "10-12",
          },
          { name: "Cable Flyes", muscleGroup: "Chest", sets: 3, reps: "12-15" },
          {
            name: "Hammer Curls",
            muscleGroup: "Biceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Cable Tricep Pushdown",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Lower Day 2",
        focus: "Lower Body",
        exercises: [
          {
            name: "Front Squat",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Sumo Deadlifts",
            muscleGroup: "Hamstrings",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Bulgarian Split Squats",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Leg Extensions",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Good Mornings",
            muscleGroup: "Hamstrings",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Seated Calf Raises",
            muscleGroup: "Calves",
            sets: 4,
            reps: "15-20",
          },
          {
            name: "Cable Crunches",
            muscleGroup: "Abs",
            sets: 3,
            reps: "15-20",
          },
        ],
      },
    ],
  },
  ppl: {
    split: "Push/Pull/Legs",
    description: "6-day split separating pushing, pulling and leg movements",
    frequency: 6,
    workouts: [
      {
        day: "Push Day 1",
        focus: "Chest, Shoulders, Triceps",
        exercises: [
          { name: "Bench Press", muscleGroup: "Chest", sets: 4, reps: "6-8" },
          {
            name: "Overhead Press",
            muscleGroup: "Shoulders",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Incline Dumbbell Press",
            muscleGroup: "Chest",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Dumbbell Lateral Raises",
            muscleGroup: "Shoulders",
            sets: 4,
            reps: "12-15",
          },
          { name: "Cable Flyes", muscleGroup: "Chest", sets: 3, reps: "12-15" },
          {
            name: "Tricep Pushdowns",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Overhead Tricep Extension",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Pull Day 1",
        focus: "Back, Biceps",
        exercises: [
          { name: "Deadlift", muscleGroup: "Back", sets: 4, reps: "5-7" },
          { name: "Pull-Ups", muscleGroup: "Back", sets: 4, reps: "Max" },
          { name: "Barbell Rows", muscleGroup: "Back", sets: 4, reps: "8-10" },
          { name: "Face Pulls", muscleGroup: "Back", sets: 4, reps: "15-20" },
          {
            name: "Lat Pulldowns",
            muscleGroup: "Back",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Barbell Curls",
            muscleGroup: "Biceps",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Hammer Curls",
            muscleGroup: "Biceps",
            sets: 3,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Legs Day 1",
        focus: "Quadriceps, Hamstrings, Calves",
        exercises: [
          {
            name: "Barbell Squat",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "6-8",
          },
          {
            name: "Romanian Deadlifts",
            muscleGroup: "Hamstrings",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Leg Press",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Leg Extensions",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Hamstring Curls",
            muscleGroup: "Hamstrings",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Standing Calf Raises",
            muscleGroup: "Calves",
            sets: 5,
            reps: "15-20",
          },
          {
            name: "Hanging Leg Raises",
            muscleGroup: "Abs",
            sets: 4,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Push Day 2",
        focus: "Chest, Shoulders, Triceps",
        exercises: [
          {
            name: "Incline Bench Press",
            muscleGroup: "Chest",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Dumbbell Shoulder Press",
            muscleGroup: "Shoulders",
            sets: 4,
            reps: "10-12",
          },
          {
            name: "Dumbbell Bench Press",
            muscleGroup: "Chest",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Cable Lateral Raises",
            muscleGroup: "Shoulders",
            sets: 4,
            reps: "12-15",
          },
          { name: "Pec Deck", muscleGroup: "Chest", sets: 3, reps: "12-15" },
          {
            name: "Close Grip Bench Press",
            muscleGroup: "Triceps",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Tricep Dips",
            muscleGroup: "Triceps",
            sets: 3,
            reps: "10-12",
          },
        ],
      },
      {
        day: "Pull Day 2",
        focus: "Back, Biceps",
        exercises: [
          { name: "Barbell Rows", muscleGroup: "Back", sets: 4, reps: "8-10" },
          {
            name: "Lat Pulldowns",
            muscleGroup: "Back",
            sets: 4,
            reps: "10-12",
          },
          { name: "T-Bar Rows", muscleGroup: "Back", sets: 4, reps: "10-12" },
          {
            name: "Seated Cable Rows",
            muscleGroup: "Back",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Reverse Flyes",
            muscleGroup: "Back",
            sets: 4,
            reps: "15-20",
          },
          {
            name: "Preacher Curls",
            muscleGroup: "Biceps",
            sets: 4,
            reps: "10-12",
          },
          {
            name: "Concentration Curls",
            muscleGroup: "Biceps",
            sets: 3,
            reps: "12-15",
          },
        ],
      },
      {
        day: "Legs Day 2",
        focus: "Quadriceps, Hamstrings, Calves",
        exercises: [
          {
            name: "Front Squat",
            muscleGroup: "Quadriceps",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Sumo Deadlifts",
            muscleGroup: "Hamstrings",
            sets: 4,
            reps: "8-10",
          },
          {
            name: "Hack Squat",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Walking Lunges",
            muscleGroup: "Quadriceps",
            sets: 3,
            reps: "12-15",
          },
          {
            name: "Good Mornings",
            muscleGroup: "Hamstrings",
            sets: 3,
            reps: "10-12",
          },
          {
            name: "Seated Calf Raises",
            muscleGroup: "Calves",
            sets: 5,
            reps: "15-20",
          },
          {
            name: "Cable Crunches",
            muscleGroup: "Abs",
            sets: 4,
            reps: "15-20",
          },
        ],
      },
    ],
  },
};